FROM apache/airflow:2.7.2

USER root
COPY requirements.txt /requirements.txt

# install as 'airflow' user, NOT root
USER airflow
RUN pip install --no-cache-dir -r /requirements.txt

COPY airflow/dags/ /opt/airflow/dags/
COPY airflow/plugins/ /opt/airflow/plugins/
